# Generated by Django 3.0.8 on 2020-08-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200825_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
