# Generated by Django 3.0.8 on 2020-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landingPage', models.CharField(default='month', max_length=10)),
                ('weekends', models.BooleanField(default=True)),
                ('firstDayweek', models.CharField(default='monday', max_length=10)),
            ],
        ),
    ]
