# Generated by Django 3.0.8 on 2020-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200902_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='firstDayweek',
            field=models.IntegerField(default=0),
        ),
    ]
