# Generated by Django 3.0.8 on 2020-09-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200902_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='firstDayweek',
            new_name='firstWeekday',
        ),
    ]
