# Generated by Django 3.0.8 on 2020-09-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200902_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='weekends',
        ),
    ]
