# Generated by Django 3.0.8 on 2020-08-01 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
