# Generated by Django 3.0.8 on 2020-08-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_auto_20200824_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitStreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('frequency', models.CharField(max_length=40)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Habit')),
            ],
        ),
    ]
