# Generated by Django 3.0.8 on 2020-08-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardStreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('unlocked', models.BooleanField(default=False)),
                ('counter', models.IntegerField()),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Reward')),
            ],
        ),
    ]
