# Generated by Django 3.0.8 on 2020-09-01 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_auto_20200831_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardstreak',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 8, 31)),
            preserve_default=False,
        ),
    ]
