# Generated by Django 3.0.8 on 2020-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_rewardstreak_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardstreak',
            name='unlockDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
