# Generated by Django 3.0.8 on 2020-09-01 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0013_rewardstreak_unlockdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardstreak',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='reward',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 8, 1)),
            preserve_default=False,
        ),
    ]
